USE biblioteca;

INSERT INTO livros (titulo, autor, editora, ano_lancamento) VALUES
('Dom Casmurro', 'Machado de Assis', 'Garnier', 1899),
('Grande Sertão: Veredas', 'Guimarães Rosa', 'José Olympio', 1956),
('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'Tipografia Nacional', 1881),
('O Cortiço', 'Aluísio Azevedo', 'B. L. Garnier', 1890),
('Capitães da Areia', 'Jorge Amado', 'José Olympio', 1937),
('Vidas Secas', 'Graciliano Ramos', 'José Olympio', 1938),
('A Hora da Estrela', 'Clarice Lispector', 'José Olympio', 1977),
('O Alienista', 'Machado de Assis', 'Garnier', 1882),
('Iracema', 'José de Alencar', 'Tipografia Viana', 1865),
('Macunaíma', 'Mário de Andrade', 'Oficinas Gráficas', 1928),
('O Tempo e o Vento', 'Erico Verissimo', 'Globo', 1949),
('Quincas Borba', 'Machado de Assis', 'Garnier', 1891),
('Menino de Engenho', 'José Lins do Rego', 'José Olympio', 1932),
('Gabriela, Cravo e Canela', 'Jorge Amado', 'Martins', 1958),
('São Bernardo', 'Graciliano Ramos', 'Ariel', 1934),
('A Moreninha', 'Joaquim Manuel de Macedo', 'Tipografia Francesa', 1844),
('O Guarani', 'José de Alencar', 'Empresa Nacional', 1857),
('Clara dos Anjos', 'Lima Barreto', 'Mérito', 1948),
('Triste Fim de Policarpo Quaresma', 'Lima Barreto', 'Tipografia do Jornal', 1915),
('A Paixão Segundo G.H.', 'Clarice Lispector', 'Editora do Autor', 1964),
('Lavoura Arcaica', 'Raduan Nassar', 'José Olympio', 1975),
('Angústia', 'Graciliano Ramos', 'José Olympio', 1936),
('Memórias de um Sargento de Milícias', 'Manuel Antônio de Almeida', 'Tipografia Nacional', 1854),
('O Quinze', 'Rachel de Queiroz', 'Editora Olympio', 1930),
('Sagarana', 'Guimarães Rosa', 'Universal', 1946),
('Fogo Morto', 'José Lins do Rego', 'José Olympio', 1943),
('Dona Flor e Seus Dois Maridos', 'Jorge Amado', 'Martins', 1966),
('Olhai os Lírios do Campo', 'Erico Verissimo', 'Globo', 1938),
('Noite na Taverna', 'Álvares de Azevedo', 'Garnier', 1855),
('Dois Irmãos', 'Milton Hatoum', 'Companhia das Letras', 2000);
